### ISSUE TITLE
checkmk apcaccess 5.2.1 extension breaks checkmk 2.2.0p7 search

### ISSUE THREAD

**Issue by cryptedx** [HeinleinSupport/check_mk_extensions#139]
Hello,

I tried to use your checkmk apcaccess 5.2.1 extension with checkmk version 2.2.0p7 raw edition. After adding and installing it I can't use the "search in setup" anymore. It just displays "Currently indexing, please try again shortly". Then I had a look at this log: `tail -f ~/var/log/web.log` and I got this:

```
    if rulespec.title
       ^^^^^^^^^^^^^^
  File "/omd/sites/cmk/lib/python3/cmk/gui/watolib/rulespecs.py", line 352, in title
    plain_title = self._title() if self._title else self.valuespec.title()
                                                    ^^^^^^^^^^^^^^
  File "/omd/sites/cmk/lib/python3/cmk/gui/watolib/rulespecs.py", line 348, in valuespec
    return self._valuespec()
           ^^^^^^^^^^^^^^^^^
  File "<string>", line 97, in _valuespec_apcaccess_inventory
NameError: name 'DropdownChoice' is not defined
```

I am not able to use the extension at all. It does not appear. 

Thanks

**Comment by SouIsAs** [comment]
Hello, just wanted to confirm that i have the exact same problem (running check_mk raw edition 2.2.0p7 and the latest mkp 5.2.1). When i disable the mkp the search starts working again, until i reenable the mkp.

I also want to add that i cannot update check_mk since version 2.2.x unless i disable this mkp (otherwise the update fails).

I think it has to do with changes since check_mk v2.2.0:

-  https://forum.checkmk.com/t/mkp-changes-in-2-2-discussion/38017/13
-  https://checkmk.com/werk/15493

Thanks for this very useful mkp!

**Comment by gurubert** [comment]
Fixed with https://github.com/HeinleinSupport/check_mk_extensions/commit/0c5775a519c3b3083a7013fce8fd096666fff9b6
