### ISSUE TITLE
cpufreq - use of scaling_cur_freq inappropriate

### ISSUE THREAD

**Issue by tomchiverton** [HeinleinSupport/check_mk_extensions#151]
On a Dell server here, the scaling_cur_freq exceeds scaling_max_freq fairly regularly :
```
# cat  /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq ; echo -- ; cat  /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq
3392895
3393756
1397416
1396725
--
2100000
2100000
2100000
2100000
```

**Comment by tomchiverton** [comment]
compare to using plain old cpuinfo_cur_freq
```
cat  /sys/devices/system/cpu/cpu*/cpufreq/cpuinfo_cur_freq ;  echo --;  cat  /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq ; echo -- ; cat  /sys/devices/system/cpu/cpu*/cpufreq/scaling_max_freq
1400000
2100000
1400000
1400000
--
3392691
3393772
1396711
1397417
--
2100000
2100000
2100000
2100000
```

**Comment by gurubert** [comment]
I do not see the file cpuinfo_cur_freq and the systems I use.
Which kernel version are you using?

**Comment by tomchiverton** [comment]
It's Fedora Core 39, 6.6.14-100.fc38.x86_64

**Comment by gurubert** [comment]
That's too new for me :)

**Comment by tomchiverton** [comment]
According to https://unix.stackexchange.com/questions/87522/why-do-cpuinfo-cur-freq-and-proc-cpuinfo-report-different-numbers it's been around for at least 10 years.

**Comment by gurubert** [comment]
On the page you linked is a paragraph:

**So what about cpuinfo_cur_freq?**
This parameter has more to do with the specification of the CPU and which profile it's currently in, rather than anything useful with respect to how the CPU is currently operating. For actual operational telemetry I'd use the scaling_* kernel tunables.

Maybe the CPU models I have are not able to report cpuinfo_cur_freq?
