### ISSUE TITLE
Usage of filehandles plugin

### ISSUE THREAD

**Issue by admlko** [HeinleinSupport/check_mk_extensions#57]
Hi,

There's no manpage for the filehandles plugin, so I think I am doing something wrong.
I have installed the latest version (4.0) which should work with 1.6, but I get the following exception when trying to run inventory:
```
Exception	
TypeError (unhashable type)

Traceback	
  File "/omd/sites/valvonta/lib/python/cmk_base/decorator.py", line 54, in wrapped_check_func
    status, infotexts, long_infotexts, perfdata = check_func(hostname, *args, **kwargs)
  File "/omd/sites/valvonta/lib/python/cmk_base/discovery.py", line 422, in check_discovery
    on_error="raise")
  File "/omd/sites/valvonta/lib/python/cmk_base/discovery.py", line 1057, in _get_host_services
    return _get_node_services(host_config, ipaddress, sources, multi_host_sections, on_error)
  File "/omd/sites/valvonta/lib/python/cmk_base/discovery.py", line 1065, in _get_node_services
    multi_host_sections, on_error)
  File "/omd/sites/valvonta/lib/python/cmk_base/discovery.py", line 1098, in _get_discovered_services
    multi_host_sections, on_error)
  File "/omd/sites/valvonta/lib/python/cmk_base/discovery.py", line 834, in _discover_services
    check_plugin_name, on_error):
  File "/omd/sites/valvonta/lib/python/cmk_base/discovery.py", line 935, in _execute_discovery
    discovered_items = _execute_discovery_function(discovery_function, section_content)
  File "/omd/sites/valvonta/lib/python/cmk_base/discovery.py", line 973, in _execute_discovery_function
    discovered_items = discovery_function(section_content)
  File "/omd/sites/valvonta/local/share/check_mk/checks/filehandles", line 82, in inventory_filehandles
    taglist, hostlist = rule[1:3]
```

Info variable gets populated correctly, and the output of the agent seems fine. It is the same format as in commented section in the beginning of the agent.

I have created one rule for it like this:
	
```
Process Name: 	%u
Process Matching: 	
Name of the User: 	
```

Not sure if it does what I want - one service per user which monitors the current file handle usage with both soft and hard limits.

CentOS 7 64-bit
CEE 1.6.0p6
Python 2.7.16

**Comment by divansantana** [comment]
@admlko did you ever make progress with this? :)

**Comment by admlko** [comment]
Sadly no, after a while I lost interest because for us this wasn't mandatory, just "nice to have" feature... Would love to see official support for this in Checkmk though.

**Comment by divansantana** [comment]
@admlko I tried it today and it just worked. 

cmk -P install /tmp/filehandles-4.0.mkp

and loaded the plugin on the agent and all was fine. 

1.6.11 server.

**Comment by gurubert** [comment]
not reproducable

**Comment by tobias-gruenewald** [comment]
I am having this same issue with Filehandles Plugin 4.0 on Checkmk 1.6.0p22.

Traceback is exactly the one shown in the original post. It only happens when I create a WATO rule of type "Filehandles Discovery", which makes sense, as only then the inventory function goes in the loop and hits line 82 of the python file.

So when using the agent plugin and check without any discovery rule, it works fine and provides the global filehandle count. But if you want to extract the filhandle for a specific process, inventory fails.

This also is independent of the content of the discovery rule, because the inventory function fails before it even parses the rule.

As far as I understand the Python code
`taglist, hostlist = rule[1:3]`
tries to read the entries 2 (taglist) and 3 (hostlist) of the rule. But the rule object is actually a dictionary and as such an unordered object in Python 2.7, so accessing the content via indexes will not work.

Can this be reopened?

I already tried to rewrite the code to access the rule content through the get() function, which works. But it fails later when trying to run hosttags_match_taglist() if the taglist is "None". I am still trying to get a working fix. If I succeed I can add a pull request.

**Comment by gurubert** [comment]
The feature "filehandles per process" was never stable. Sorry that it made it into the repo.

In the latest CheckMK version there is an upstream agent plugin `mk_filehandler` that does the job of checking total filehandles. That's why our plugin will be deprecated and will not receive any updates.

**Comment by tobias-gruenewald** [comment]
Thanks for the update. I am aware of `mk_filehandler`, but we actually needed filehandles per process to monitor a buggy third-party application that accumulates filehandles and crashes after reaching a limit.

I was able to modify the Python files, so the plugin works as expected in our environment. So my goal has been achieved and I am glad that you created that plugin/check in the first place even though it was not fully done.

I understand that it will not be updated in the future, though.
