### ISSUE TITLE
huawei plugin checkmk v2

### ISSUE THREAD

**Issue by fabiankhh** [HeinleinSupport/check_mk_extensions#80]
The Huawei plugin does not work with version 2.
Is there an adaptation planned?

**Comment by fabiankhh** [comment]
And of course thanks for your good work and the numerous plugins.

**Comment by gurubert** [comment]
The SNMP agent of Huawei storage devices is not performant enough. Because of that the development of the SNMP checks has been deprecated.

There is an extension that uses the HTTP API of the Huawei storage systems for monitoring available from https://www.comnetgmbh.com/

**Comment by andresin** [comment]
I know this issue is closed, but I am having the same problem and consider my findings can be of some help to others.

I don't have a full replacement for the huawei cmk package, but regarding the pure monitoring part I would recomend this:

https://github.com/tcomerma/check_oceanstor

It also uses the REST API but is far more complete that what I could find in comnetgmbh Github (https://github.com/comnetgmbh).

If Comnet Gmbh has a better replacement for Heinslein's Huawei package, I would appreciate if it could be shared.
